<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Guara.Hosting\Guara.Hosting.csproj" />
    <ProjectReference Include="..\..\src\Guara.Scheduler\Guara.Scheduler.csproj" />
    <ProjectReference Include="..\..\src\Guara.Dispatcher\Guara.Dispatcher.csproj" />
    <ProjectReference Include="..\..\src\Guara.Worker\Guara.Worker.csproj" />
    <ProjectReference Include="..\..\src\Guara.Executor\Guara.Executor.csproj" />
    <ProjectReference Include="..\..\src\Guara.Storage.Memory\Guara.Storage.Memory.csproj" />
    <ProjectReference Include="..\..\src\Guara.Storage.PostgreSql\Guara.Storage.PostgreSql.csproj" />
    <ProjectReference Include="..\..\src\Guara.Storage.SqlServer\Guara.Storage.SqlServer.csproj" />
    <ProjectReference Include="..\..\src\Guara.Storage.MySql\Guara.Storage.MySql.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Npgsql" />
    <PackageReference Include="Testcontainers.MsSql" />
    <PackageReference Include="Testcontainers.MySql" />
    <PackageReference Include="Testcontainers.PostgreSql" />
  </ItemGroup>

</Project>
