<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <UserSecretsId>guara-host</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Guara.Diagnostics\Guara.Diagnostics.csproj" />
    <ProjectReference Include="..\..\src\Guara.Hosting\Guara.Hosting.csproj" />
    <ProjectReference Include="..\..\src\Guara.Server\Guara.Server.csproj" />
    <ProjectReference Include="..\..\src\Guara.Storage.Memory\Guara.Storage.Memory.csproj" />
    <ProjectReference Include="..\..\src\Guara.Storage.PostgreSql\Guara.Storage.PostgreSql.csproj" />
    <ProjectReference Include="..\..\src\Guara.SourceGenerators\Guara.SourceGenerators.csproj"
                      OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" />
  </ItemGroup>

  <ItemGroup>
    <None Include="appsettings*.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
