using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace Guara.SourceGenerators;

/// <summary>
/// Emitter do pipeline: recebe os modelos equatable e produz o arquivo gerado —
/// registro em DI (<c>AddGuaraJobs</c>), módulo com invocação sem reflection e
/// metadados dos atributos, structs de argumentos (JSON direto) e factories tipadas
/// de descritor. Saída determinística: mesma entrada → mesmo texto.
/// </summary>
public static class JobEmitter
{
    /// <summary>Gera o código do assembly a partir dos jobs descobertos.</summary>
    /// <param name="jobs">Modelos coletados (podem conter diagnósticos).</param>
    /// <param name="assemblyName">Nome do assembly alvo (vira o namespace gerado).</param>
    /// <param name="reportDiagnostic">Callback de diagnóstico.</param>
    /// <returns>O texto do arquivo gerado, ou <c>null</c> quando não há nada a emitir.</returns>
    public static string? Emit(
        ImmutableArray<JobModel?> jobs, string assemblyName,
        System.Action<DiagnosticModel> reportDiagnostic)
    {
        var valid = new List<JobModel>();
        foreach (var job in jobs)
        {
            if (job is null)
            {
                continue;
            }

            foreach (var diagnostic in job.Diagnostics)
            {
                reportDiagnostic(diagnostic);
            }

            if (job.Diagnostics.Count == 0)
            {
                valid.Add(job);
            }
        }

        // Discriminador duplicado é erro: dois jobs não podem responder pela mesma chave.
        var duplicates = valid
            .GroupBy(job => $"{job.TypeName}.{job.MethodName}")
            .Where(group => group.Count() > 1)
            .ToList();
        foreach (var group in duplicates)
        {
            foreach (var job in group)
            {
                reportDiagnostic(new DiagnosticModel(
                    JobDiagnostics.DuplicateJob.Id, job.Location, new EquatableArray<string>([group.Key])));
            }

            valid.RemoveAll(job => $"{job.TypeName}.{job.MethodName}" == group.Key);
        }

        if (valid.Count == 0)
        {
            return null;
        }

        valid.Sort((a, b) => string.CompareOrdinal(
            $"{a.TypeName}.{a.MethodName}", $"{b.TypeName}.{b.MethodName}"));

        var ns = SanitizeNamespace(assemblyName);
        var builder = new StringBuilder();
        builder.Append($$"""
            // <auto-generated/>
            // Gerado pelo Guara.SourceGenerators — não edite.
            #nullable enable
            namespace {{ns}};

            /// <summary>Registro dos jobs [GuaraJob] deste assembly (gerado em compilação).</summary>
            public static class GuaraJobsRegistration
            {
                /// <summary>
                /// Registra os jobs descobertos: classes no DI e o módulo de invocação
                /// (sem reflection) com os metadados declarados nos atributos.
                /// </summary>
                /// <param name="builder">Builder do Guará.</param>
                /// <returns>O próprio builder, para encadeamento fluente.</returns>
                public static global::Guara.Abstractions.IGuaraBuilder AddGuaraJobs(
                    this global::Guara.Abstractions.IGuaraBuilder builder)
                {

            """);

        foreach (var typeFullName in valid.Where(j => !j.IsStatic).Select(j => j.TypeFullName).Distinct())
        {
            builder.AppendLine(
                $"        global::Microsoft.Extensions.DependencyInjection.Extensions." +
                $"ServiceCollectionDescriptorExtensions.TryAddTransient<{typeFullName}>(builder.Services);");
        }

        builder.Append("""
                    global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddEnumerable(
                        builder.Services,
                        global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Singleton<global::Guara.Executor.IJobModule>(new GuaraGeneratedJobModule()));
                    return builder;
                }
            }

            /// <summary>Módulo gerado: handlers e metadados de cada job.</summary>
            internal sealed class GuaraGeneratedJobModule : global::Guara.Executor.IJobModule
            {
                /// <inheritdoc />
                public void Register(global::Guara.Executor.JobHandlerRegistry registry)
                {

            """);

        foreach (var job in valid)
        {
            EmitRegistration(builder, job);
        }

        builder.AppendLine("    }");
        builder.AppendLine("}");

        foreach (var job in valid)
        {
            EmitArgsStruct(builder, job);
        }

        foreach (var group in valid.GroupBy(j => j.TypeShortName))
        {
            EmitFactory(builder, group.Key, [.. group]);
        }

        return builder.ToString();
    }

    private static void EmitRegistration(StringBuilder builder, JobModel job)
    {
        var args = job.SerializableParameters.ToList();
        var argsRead = args.Count > 0
            ? $"            var args = {job.SafeName}Args.Read(context.Descriptor.Arguments);\n"
            : "";
        var instance = job.IsStatic
            ? job.TypeFullName
            : "job";
        var resolve = job.IsStatic
            ? ""
            : $"            var job = global::Microsoft.Extensions.DependencyInjection." +
              $"ServiceProviderServiceExtensions.GetRequiredService<{job.TypeFullName}>(services);\n";

        var callArgs = new List<string>();
        foreach (var parameter in job.Parameters)
        {
            callArgs.Add(parameter.IsCancellationToken ? "ct" : $"args.{Pascal(parameter.Name)}");
        }

        var call = $"{instance}.{job.MethodName}({string.Join(", ", callArgs)})";
        var invoke = job.ReturnKind switch
        {
            ReturnKind.Task => $"            return new global::System.Threading.Tasks.ValueTask({call});",
            ReturnKind.ValueTask => $"            return {call};",
            _ => $"            {call};\n            return default;",
        };

        builder.AppendLine($$"""
                    registry.Register(
                        "{{job.TypeName}}", "{{job.MethodName}}",
                        new global::Guara.Executor.JobExecutionMetadata
                        {
                            Queue = {{Literal(job.Queue)}},
                            MaxAttempts = {{(job.MaxAttempts is { } m ? m.ToString() : "null")}},
                            TimeoutSeconds = {{(job.TimeoutSeconds is { } t ? t.ToString() : "null")}},
                            SkipIfPreviousRunning = {{(job.SkipIfPreviousRunning ? "true" : "false")}},
                            ConcurrencyKey = {{EmitConcurrencyKey(job)}},
                            ConcurrencyWaitSeconds = {{job.ConcurrencyWaitSeconds}},
                        },
                        static (services, context, ct) =>
                        {
            {{argsRead}}{{resolve}}{{invoke}}
                        });
            """);
    }

    private static string EmitConcurrencyKey(JobModel job)
    {
        if (!job.DisableConcurrency)
        {
            return "null";
        }

        if (job.ConcurrencyKeyTemplate is null)
        {
            return $"static _ => \"{job.TypeName}.{job.MethodName}\"";
        }

        var args = job.SerializableParameters.ToList();
        if (args.Count == 0)
        {
            return $"static _ => {Literal(job.ConcurrencyKeyTemplate)}";
        }

        var formatArgs = string.Join(", ", args.Select(a => $"args.{Pascal(a.Name)}"));
        return $$"""
            static context =>
                        {
                            var args = {{job.SafeName}}Args.Read(context.Descriptor.Arguments);
                            return string.Format(global::System.Globalization.CultureInfo.InvariantCulture, {{Literal(job.ConcurrencyKeyTemplate)}}, {{formatArgs}});
                        }
            """;
    }

    private static void EmitArgsStruct(StringBuilder builder, JobModel job)
    {
        var args = job.SerializableParameters.ToList();
        if (args.Count == 0)
        {
            return;
        }

        builder.AppendLine($$"""

            /// <summary>Argumentos serializados de <c>{{job.TypeName}}.{{job.MethodName}}</c> (JSON posicional).</summary>
            internal readonly struct {{job.SafeName}}Args
            {
            """);

        foreach (var arg in args)
        {
            builder.AppendLine($"    public readonly {arg.FullTypeName} {Pascal(arg.Name)};");
        }

        var ctorParams = string.Join(", ", args.Select(a => $"{a.FullTypeName} @{a.Name}"));
        builder.AppendLine($$"""

                public {{job.SafeName}}Args({{ctorParams}})
                {
            """);
        foreach (var arg in args)
        {
            builder.AppendLine($"        {Pascal(arg.Name)} = @{arg.Name};");
        }

        builder.AppendLine($$"""
                }

                public static global::System.ReadOnlyMemory<byte> Write({{ctorParams}})
                {
                    var buffer = new global::System.Buffers.ArrayBufferWriter<byte>();
                    using var writer = new global::System.Text.Json.Utf8JsonWriter(buffer);
                    writer.WriteStartArray();
            """);
        foreach (var arg in args)
        {
            builder.AppendLine($"        {arg.WriterStatement}");
        }

        builder.AppendLine($$"""
                    writer.WriteEndArray();
                    writer.Flush();
                    return buffer.WrittenMemory;
                }

                public static {{job.SafeName}}Args Read(global::System.ReadOnlyMemory<byte> data)
                {
                    var reader = new global::System.Text.Json.Utf8JsonReader(data.Span);
                    reader.Read(); // início do array
            """);
        foreach (var arg in args)
        {
            builder.AppendLine($"        reader.Read();");
            builder.AppendLine($"        var @{arg.Name} = {arg.ReaderExpression};");
        }

        var ctorArgs = string.Join(", ", args.Select(a => $"@{a.Name}"));
        builder.AppendLine($$"""
                    return new {{job.SafeName}}Args({{ctorArgs}});
                }
            }
            """);
    }

    private static void EmitFactory(StringBuilder builder, string typeShortName, List<JobModel> jobs)
    {
        builder.AppendLine($$"""

            /// <summary>Descritores tipados dos jobs de <c>{{jobs[0].TypeName}}</c> — assinatura errada é erro de compilação.</summary>
            public static class {{typeShortName}}Guara
            {
            """);

        foreach (var job in jobs)
        {
            var args = job.SerializableParameters.ToList();
            var parameters = string.Join(", ", args.Select(a => $"{a.FullTypeName} @{a.Name}"));
            var arguments = args.Count > 0
                ? $"{job.SafeName}Args.Write({string.Join(", ", args.Select(a => $"@{a.Name}"))})"
                : "default";
            var queue = Literal(job.Queue ?? "default");

            builder.AppendLine($"""
                    /// <summary>Descritor de <c>{job.MethodName}</c>, com fila e argumentos resolvidos em compilação.</summary>
                    public static global::Guara.Abstractions.JobDescriptor {job.MethodName}({parameters})
                        => new("{job.TypeName}", "{job.MethodName}", {arguments}, {queue});
            """);
        }

        builder.AppendLine("}");
    }

    private static string Pascal(string name)
        => name.Length == 0 ? name : char.ToUpperInvariant(name[0]) + name.Substring(1);

    private static string Literal(string? value)
        => value is null ? "null" : $"\"{value.Replace("\\", "\\\\").Replace("\"", "\\\"")}\"";

    private static string SanitizeNamespace(string assemblyName)
    {
        var segments = assemblyName.Split('.');
        var builder = new StringBuilder();
        for (var i = 0; i < segments.Length; i++)
        {
            if (i > 0)
            {
                builder.Append('.');
            }

            var segment = new string([.. segments[i].Select(c => char.IsLetterOrDigit(c) || c == '_' ? c : '_')]);
            if (segment.Length == 0 || char.IsDigit(segment[0]))
            {
                segment = "_" + segment;
            }

            builder.Append(segment);
        }

        return builder.ToString();
    }
}
